# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyong', '0002_auto_20180701_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_line_log',
            field=models.IntegerField(default=0),
        ),
    ]
